#Uploading the client file and model

In [3]:
import pandas as pd
df=pd.read_csv('/content/Areas - Sheet1.csv')
df

    Area
0   1000
1   1400
2   2000
3   2700
4   3100
5   3600
6   4200
7   4450
8   4800
9   5500
10  5900
11  6600

In [4]:
#we have to activate the ML model
import pickle
with open('/content/ukkadamareamodel','rb') as f:
  reg=pickle.load(f)

#Predict the data

In [5]:
reg.predict([[2500]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"

array([13683684.21052631])

In [6]:
pricedf=reg.predict(df)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Area
Feature names seen at fit time, yet now missing:
- area

  warnings.warn(message, FutureWarning)

In [7]:
df['price']=pricedf
df

    Area         price
0   1000  2.935789e+06
1   1400  5.801895e+06
2   2000  1.010105e+07
3   2700  1.511674e+07
4   3100  1.798284e+07
5   3600  2.156547e+07
6   4200  2.586463e+07
7   4450  2.765595e+07
8   4800  3.016379e+07
9   5500  3.517947e+07
10  5900  3.804558e+07
11  6600  4.306126e+07

In [8]:
df.to_csv('clientoutput.csv',index=False)